name: PuppyMatch
description: Primera aplicación con flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  dropdown_textfield: ^1.0.8
  calendar_date_picker2: ^0.5.2
  image_picker: ^0.8.7+4
  email_validator: ^2.1.17
  firebase_auth: ^4.6.1
  firebase_core: ^2.12.0
  firebase_storage: ^11.2.1
  cloud_firestore: ^4.7.1
  readmore: ^2.1.0
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  flutter_launcher_icons: ^0.13.1
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9
  loading_animation_widget: ^1.2.0+4
  deep_route: ^0.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/puppy_match.png"

  flutter_lints: ^2.0.0


flutter:
  fonts:
    - family: Kinder
      fonts:
        - asset: fonts/kindergarten.ttf

  uses-material-design: true

  assets:
    - assets/logo_doggy.png
    - assets/puppy_match.png
    - assets/puppy_match-2.png
    - assets/golden-retriever.jpg
    - assets/pup.jpg
    - assets/icono_perfil.png


