
List<String> razasDePerro = [
  "Mestizo",
  "Akita Inu",
  "Bulldog",
  "Bulldog Francés",
  "Caniche",
  "Dálmata",
  "Golden Retriever",
  "Labrador Retriever",
  "Pomerania",
  "Pastor Alemán",
  "Pug",
  "Rottweiler",
  "San Bernardo",
  "Shih Tzu",
  "Bichón Frisé",
  "Bichón Maltés",
  "Border Collie",
  "Bull Terrier",
  "Chihuahua",
  "Chow Chow",
  "Cocker Spaniel",
  "Dóberman",
  "Dóberman Pinscher",
  "Dogo Argentino",
  "Dogo de Burdeos",
  "Galgo Español",
  "Gran Danés",
  "Husky Siberiano",
  "Jack Russell Terrier",
  "Mastín Español",
  "Mastín Napolitano",
  "Papillon",
  "Pastor Belga",
  "Pastor de Shetland",
  "Pequinés",
  "Perro de Agua Español",
  "Perro Lobo Checoslovaco",
  "Perro Lobo de Saarloos",
  "Pointer",
  "Presa Canario",
  "Samoyedo",
  "Schnauzer",
  "Setter Irlandés",
  "Shar Pei",
  "Springer Spaniel",
  "Terranova",
  "Weimaraner",
  "West Highland White Terrier",
  "Whippet",
  "Xoloitzcuintli",
  "Yorkshire Terrier",
  "Affenpinscher",
  "Basset Hound",
  "Beagle",
  "Belga Malinois",
  "Bóxer",
  "Boyero de Berna",
  "Boykin Spaniel",
  "Braco de Weimar",
  "Braco Húngaro",
  "Braco Italiano",
  "Braco Saint Germain",
  "Bullmastiff",
  "Cairn Terrier",
  "Cane Corso",
  "Cavalier King Charles Spaniel",
  "Cimarrón Uruguayo",
  "Cirneco del Etna",
  "Clumber Spaniel",
  "Corgi Galés",
  "Dachshund",
  "Deerhound Escocés",
  "Drentse Patrijshond",
  "Dunker Noruego",
  "Eurasier",
  "Field Spaniel",
  "Fila Brasileño",
  "Flat Coated Retriever",
  "Fox Terrier",
  "Gos d'Atura Català",
  "Gran Boyero Suizo",
  "Gran Perro Japonés",
  "Hokkaido",
  "Hovawart",
  "Ibizan Hound",
  "Irish Terrier",
  "Irish Water Spaniel",
  "Kai Ken",
  "Klee Kai",
  "Komondor",
  "Kuvasz",
  "Laika",
  "Leonberger",
  "Lundehund",
  "Löwchen",
  "Malinois",
  "Maltés",
  "Mastiff",
];


