
List<String> razasDePerro = [
  "Mestizo",
  "Affenpinscher",
  "Akita Inu",
  "Basset Hound",
  "Beagle",
  "Belga Malinois",
  "Bichón Frisé",
  "Bichón Maltés",
  "Bóxer",
  "Border Collie",
  "Bouvier Bernois",
  "Boyero de Berna",
  "Boykin Spaniel",
  "Braco de Weimar",
  "Braco Húngaro",
  "Braco Italiano",
  "Braco Saint Germain",
  "Briard",
  "Bulldog",
  "Bulldog Francés",
  "Bullmastiff",
  "Bull Terrier",
  "Cairn Terrier",
  "Cane Corso",
  "Cavalier King Charles Spaniel",
  "Chihuahua",
  "Chow Chow",
  "Cimarrón Uruguayo",
  "Cirneco del Etna",
  "Clumber Spaniel",
  "Cocker Spaniel",
  "Corgi Galés",
  "Dachshund",
  "Dalmata",
  "Deerhound Escocés",
  "Dogo Argentino",
  "Dogo de Burdeos",
  "Doberman Pinscher",
  "Drentse Patrijshond",
  "Dunker Noruego",
  "Eurasier",
  "Field Spaniel",
  "Fila Brasileño",
  "Flat Coated Retriever",
  "Fox Terrier",
  "Galgo Español",
  "Gos d'Atura Català",
  "Golden Retriever",
  "Gran Boyero Suizo",
  "Gran Danés",
  "Gran Perro Japonés",
  "Hokkaido",
  "Hovawart",
  "Husky Siberiano",
  "Ibizan Hound",
  "Irish Terrier",
  "Irish Water Spaniel",
  "Jack Russell Terrier",
  "Kai Ken",
  "Klee Kai",
  "Komondor",
  "Kuvasz",
  "Labrador Retriever",
  "Laika",
  "Leonberger",
  "Lundehund",
  "Löwchen",
  "Malinois",
  "Maltés",
  "Mastiff",
  "Mastín Español",
  "Mastín Napolitano",
  "Pastor Alemán",
  "Pastor Belga",
  "Pastor de Shetland",
  "Pastor Vasco",
  "Papillon",
  "Pequinés",
  "Perro de Agua Español",
  "Perro Lobo Checoslovaco",
  "Perro Lobo de Saarloos",
  "Pointer",
  "Pomerania",
  "Presa Canario",
  "Pug",
  "Rottweiler",
  "San Bernardo",
  "Samoyedo",
  "Schnauzer",
  "Setter Irlandés",
  "Shar Pei",
  "Shih Tzu",
  "Spitz Japonés",
  "Springer Spaniel",
  "Terranova",
  "Weimaraner",
  "West Highland White Terrier",
  "Whippet",
  "Xoloitzcuintli",
  "Yorkshire Terrier"
];


