// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBkn5o85GLVnQtLHzD0sAFiA546agAca0',
    appId: '1:1021609599018:web:8b85bbfe214c23e23fe353',
    messagingSenderId: '1021609599018',
    projectId: 'puppy-match',
    authDomain: 'puppy-match.firebaseapp.com',
    databaseURL: 'https://puppy-match-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'puppy-match.appspot.com',
    measurementId: 'G-6X92VQK2GH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx2S4IoBrxZ87Hk8OtsTPqzqdYeWVgqXc',
    appId: '1:1021609599018:android:52bae7284c50c59a3fe353',
    messagingSenderId: '1021609599018',
    projectId: 'puppy-match',
    databaseURL: 'https://puppy-match-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'puppy-match.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIOijkpzsmOCKQX6yqcpTeUBnrJXKYkVs',
    appId: '1:1021609599018:ios:caa441d54e0b2a4e3fe353',
    messagingSenderId: '1021609599018',
    projectId: 'puppy-match',
    databaseURL: 'https://puppy-match-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'puppy-match.appspot.com',
    iosClientId: '1021609599018-r57kvl0v97qbta3ufta0dg53nvq9oias.apps.googleusercontent.com',
    iosBundleId: 'com.example.tutorial3Flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIOijkpzsmOCKQX6yqcpTeUBnrJXKYkVs',
    appId: '1:1021609599018:ios:caa441d54e0b2a4e3fe353',
    messagingSenderId: '1021609599018',
    projectId: 'puppy-match',
    databaseURL: 'https://puppy-match-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'puppy-match.appspot.com',
    iosClientId: '1021609599018-r57kvl0v97qbta3ufta0dg53nvq9oias.apps.googleusercontent.com',
    iosBundleId: 'com.example.tutorial3Flutter',
  );
}
